---
- name: Prepare container
  hosts: all
  gather_facts: true

  roles:
    - role: buluma.bootstrap
    - role: buluma.ca_certificates

  tasks:
    - name: apt update
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - gnupg
      when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" ) or
            ( ansible_os_family == "Debian" and ansible_distribution_major_version == "10" )
